### ISSUE TITLE
work offline without HA

### ISSUE THREAD

**Issue by garudaonekh** [madl3x/miflora_rbs#3]
Hi, can we use this without HA?  and without the Internet connection thus MQTT is not connected. So we only need to have the display.

For farm, it is important to be flexible and keep working in offline environment

**Comment by amircescu-gpfw** [comment]
> Hi, can we use this without HA?

Yes, HA is only an addition. It sends data via MQTT, if there is no HA server that receives that data, the station is fine with that.

> and without the Internet connection

It doesn't require an internet connection, only a WiFi connection, and an MQTT server that runs locally (in the same network).

> thus MQTT is not connected

The main objective of this project is to have multiple stations collaborating over MQTT. You can see this from the project's main banner. Therefore, removing MQTT client support from the project or making it optional, will not happen. 

But, if you don't have an MQTT server, the station will work anyway and it will display the data that it collects on the LCD screen, so it fits your needs.

> For farm, it is important to be flexible and keep working in offline environment

I don't know what you mean by "farm".

**Comment by amircescu-gpfw** [comment]
I am glad that you are asking questions about this project, but the "Issues" section is for raising bugs and problems for when you are building or using the project.

@garudaonekh Have you used or built this project yet?

**Comment by garudaonekh** [comment]
Not yet build yours. Anyhow, I have used several Miflora sensors on other projects both Esp32  and RPI.

**Comment by garudaonekh** [comment]
The problem I am facing with this sensor is its range. Normally, 20 meters from the controller. I also use Esp wroom-32U with external antenna but not much range improvement. My goal is 50~80 meters so that it can fit in greenhouse

**Comment by amircescu-gpfw** [comment]
I don't think BLE can handle that. Especially if you have obstacles.

I recommend you the following setup:
* build 2 stations, one that is simple (without enclosure, LCD, buttons, maybe only the DHT sensor) and one that is complete (with enclosure, LCD, buttons, etc).
* place the simple station closest to the sensors, to collect data from the plants
* plane the complete station where you want to view that data
* run an MQTT server on your WiFi network (you can use a HA addon for that)
* configure them both to connect to the WiFi network and MQTT server

This way your 50-80 meters can be achieved using WiFi range, which is definitely much better than BLE's range.

**Comment by madl3x** [comment]
> Hi, can we use this without HA? and without the Internet connection thus MQTT is not connected. So we only need to have the display.

Yes, HA is an addition, not a requirement.
An internet connection is also not required, only an WiFi network and an MQTT broker accessible from within that network.

> The problem I am facing with this sensor is its range. Normally, 20 meters from the controller. I also use Esp wroom-32U with external antenna but not much range improvement. My goal is 50~80 meters so that it can fit in greenhouse

You can build 2 stations, connect them to the same WIFi and MQTT broker. This way you can use the WiFi's abitity to have a better range for monitoring your plants.

Place one station close the plants were you have MiFlora sensors, and the other one where you want to see the data on display. For the first station you can use the ESP32 without anything else connected (no LCD, no buttons, no DHT sensor). This will be the station collecting data over BLE. For the other one you can build it as indicated by the intstructions (i.e. with LCD attached, buttons panel, etc.).

_LE: I had to repost this, I used a wrong account the first time_
